extends SceneTree
## Prepare the current journal pixels and icon alpha bounds without art edits.
const Main := preload("res://scripts/main.gd")
const SkillNode := preload("res://scripts/ui/grower_journal_skill_node.gd")
const Catalog := preload("res://scripts/plant_catalog_repository.gd")
const DESTINATION := "res://assets/ui/prepared_startup"

func _initialize() -> void:
	DirAccess.make_dir_recursive_absolute(DESTINATION)
	var game := Main.new()
	var code := "extends RefCounted\n## Generated by tools/bake_startup_icons.gd; original art remains unchanged.\n\nconst JOURNAL_TEXTURES := {\n"
	for id in Main.GROWER_JOURNAL_BADGE_IDS:
		var source := game._grower_journal_badge_texture(id)
		var image := SkillNode.normalized_icon_image(source)
		image.clear_mipmaps()
		var output := DESTINATION.path_join(id + ".png")
		if image.save_png(output) != OK:
			push_error("Journal icon bake failed: " + id)
			quit(1)
			return
		code += "\t\"%s\": preload(\"%s\"),\n" % [source.resource_path, output]
	code += "}\n\nconst ALPHA_BOUNDS := {\n"
	var paths := {}
	for profile in Catalog.new().load_catalog().values():
		for key in ["seed_preview_texture", "herbarium_texture"]:
			paths[str(profile[key])] = true
	for texture in [Main.WaterIcon, Main.SunIcon, Main.WindIcon, Main.FertilizerIcon, Main.NavPlantIcon, Main.NavStorageIcon]:
		paths[texture.resource_path] = true
	for path in paths:
		var texture := load(path) as Texture2D
		var image := texture.get_image()
		var rect := image.get_used_rect()
		code += "\t\"%s\": {\"rect\": Rect2i(%d, %d, %d, %d), \"size\": Vector2i(%d, %d)},\n" % [path, rect.position.x, rect.position.y, rect.size.x, rect.size.y, image.get_width(), image.get_height()]
	code += "}\n"
	var file := FileAccess.open("res://scripts/ui/prepared_startup_icons.gd", FileAccess.WRITE)
	if file == null:
		quit(1)
		return
	file.store_string(code)
	game.free()
	print("STARTUP_ICON_BAKE=PASSED journal=%d bounds=%d" % [Main.GROWER_JOURNAL_BADGE_IDS.size(), paths.size()])
	quit()
